Repository coreycartercodes/Crate, pull requests merged in 2020-12, with the labels that each got.

#19 Install packages
  .gitignore
  code/api/.gitignore
  code/web/package-lock.json
  code/web/package.json
  code/web/src/setup/store.js
  package-lock.json
Labels: Chore, Full-Stack, Priority 1

#49 Profile testing
  code/web/package-lock.json
  code/web/package.json
  code/web/src/modules/user/tests/Profile.test.js
  code/web/src/setup/store.js
  code/web/test-utils.js
Labels: Front-End, Priority 1, Profile, Testing

#55 Edit component taylor
  code/api/src/config/tests/crateQuery.test.js
  code/api/src/config/tests/productMutation.test.js
  code/api/src/config/tests/productQuery.test.js
  code/api/src/config/tests/userQuery.test.js
  code/api/src/modules/user/mutations.js
  code/api/src/modules/user/resolvers.js
  code/mobile/src/modules/user/api/actions.js
  code/web/src/modules/user/Edit.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/setup/routes/user.js
  code/web/src/setup/store.js
Labels: Editing Page, Front-End

#56 Profile information
  code/web/src/modules/user/Closet.js
  code/web/src/modules/user/Crates.js
  code/web/src/modules/user/Edit.js
  code/web/src/modules/user/Profile.js
  code/web/src/modules/user/api/actions.js
  code/web/src/setup/routes/user.js
Labels: Editing Page, Front-End, Priority 1, Product History, Profile, Upcoming Delivery, enhancement

#68 User tests
  code/web/package-lock.json
  code/web/src/modules/product/Related.test.js
  code/web/src/modules/user/Edit.js
  code/web/src/modules/user/Edit.test.js
  code/web/src/modules/user/Profile.test.js
  code/web/src/modules/user/api/actions.js
  code/web/src/modules/user/api/state.js
  code/web/src/modules/user/api/state.test.js
  code/web/src/modules/user/tests/Profile.test.js
  code/web/src/setup/store.js
Labels: enhancement
